### PR TITLE
add dependency status

### PR DESCRIPTION
**Pull request by thailekha**
JIRA: https://issues.jboss.org/browse/FH-2771

### CODE REVIEW

**Review by rachael-oregan — APPROVED** [review]

**Comment by rachael-oregan** [comment]
Retest this please

**Comment by rachael-oregan** [comment]
Retest this please

**Comment by danielpassos** [comment]
@thailekha @rachael-oregan You can ignore the test for now. It's going to be fixed by @jhellar and @corinnekrych here => https://github.com/feedhenry-templates/appforms-datasources-mongodb/pull/44

**Comment by danielpassos** [comment]
@rachael-oregan _Retest this please_ does not work for @travis-ci, only to Jenkins. If you really want to restart it you should do it in travis console closing and reopening this issue

**Comment by rachael-oregan** [comment]
@danielpassos ok I wasn't too sure about that either. Thanks

**Pull request merged**
