### PR TITLE
Test using local MongoDB, removed grunt --force

### PR DESCRIPTION
**Pull request by psturc**
### Motivation

After running `npm test`, test results show 1 error, but because of `--force` option in Grunt's settings, it is transformed into a warning, which is not taken as an error (e.g. Travis CI build passes).

```
Running "shell:unit" (shell) task
2016-06-07 14:29:56 INFO FH_MBAAS_TYPE=undefined
2016-06-07 14:29:56 DEBUG no way to determine mongo connection string


App started at: Thu Jul 07 2016 14:29:56 GMT+0200 (CEST) on port: 8001
2016-06-07 14:29:57 INFO FH_MBAAS_TYPE=undefined
2016-06-07 14:29:57 DEBUG no way to determine mongo connection string
  ✓ test express app listen is called (235ms)
  ✓ test all mbaas routes are mounted
  ✓ test all mbaas setup functions are called
  ✓ test all required middleware is added to express
info: response body:  [ { assets:
     [ 'Office Chairs',
       'Office Desks',
       'Air conditioner',
       'Dell Desktops',
       'Dell Laptop',
       'MacBook Pro 15 inch',
       'HP Laser Printer',
       'Microsoft Office 2010' ] } ]
  1) test returned months data

  4 passing (310ms)
  1 failing

  1)  test returned months data:
     Uncaught AssertionError: first key is 0
      at test/unit/test-static-route.js:63:12
      at Test.assert (node_modules/supertest/lib/test.js:194:3)
      at node_modules/supertest/lib/test.js:120:10
      at Test.Request.callback (node_modules/supertest/node_modules/superagent/lib/node/index.js:628:30)
      at Test.<anonymous> (node_modules/supertest/node_modules/superagent/lib/node/index.js:131:10)
      at IncomingMessage.<anonymous> (node_modules/supertest/node_modules/superagent/lib/node/index.js:773:12)
      at _stream_readable.js:944:16



Warning: Command failed:  Use --force to continue.

Aborted due to warnings.
```
### Comments
- I'm not sure about removing [all of the code](https://github.com/psturc/appforms-datasources-mongodb/blob/fe52b795a1399bf2af18b733abaf49a455cebe0b/test/unit/test-static-route.js) in the test which was implemented previously. Maybe @lholmquist will have some comments on it? :)
- I've also added a "fix" to the `.travis.yml` file for the MongoDB not-starting issue as mentioned [here](https://github.com/travis-ci/travis-ci/issues/5948)
### Ping

@AdamSaleh @luigizuccarelli @philbrookes

### CODE REVIEW

**Comment by luigizuccarelli** [comment]
@psturc - so does that one liner actually start a mongodb service - if so very neat :)

**Comment by psturc** [comment]
@luigizuccarelli Fortunately, it was that simple :) (one liner + [this weird fix](https://github.com/travis-ci/travis-ci/issues/5948)).

**Comment by luigizuccarelli** [comment]
@psturc Impressive - I'm a big travis fan !!!

**Comment by matzew** [comment]
@luigizuccarelli are we happy to merge this ?

**Comment by luigizuccarelli** [comment]
@matzew @psturc - Yes go ahead and merge

**Pull request merged**
